//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.93")]
public enum IncidentState
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Resolved = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cancelled = 2,
}

/// <summary>
/// אירוע בקשת השירות המשויך לחוזה.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("incident")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.93")]
public partial class Incident : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public Incident() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "incident";
	
	public const string EntityLogicalCollectionName = "incidents";
	
	public const string EntitySetName = "incidents";
	
	public const int EntityTypeCode = 112;
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של תיק הלקוח שאליו משויך האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")]
	public Microsoft.Xrm.Sdk.EntityReference AccountId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("accountid");
		}
	}
	
	/// <summary>
	/// תכונה זו משמשת לדוגמאות של תהליכים עסקיים של שירותים.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activitiescomplete")]
	public System.Nullable<bool> ActivitiesComplete
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("activitiescomplete");
		}
		set
		{
			this.OnPropertyChanging("ActivitiesComplete");
			this.SetAttributeValue("activitiescomplete", value);
			this.OnPropertyChanged("ActivitiesComplete");
		}
	}
	
	/// <summary>
	/// הקלד את מספר יחידות השירות שנדרשו בפועל כדי לפתור את האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("actualserviceunits")]
	public System.Nullable<int> ActualServiceUnits
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("actualserviceunits");
		}
		set
		{
			this.OnPropertyChanging("ActualServiceUnits");
			this.SetAttributeValue("actualserviceunits", value);
			this.OnPropertyChanged("ActualServiceUnits");
		}
	}
	
	/// <summary>
	/// הקלד את מספר יחידות השירות שלפיהן חויב הלקוח עבור האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billedserviceunits")]
	public System.Nullable<int> BilledServiceUnits
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("billedserviceunits");
		}
		set
		{
			this.OnPropertyChanging("BilledServiceUnits");
			this.SetAttributeValue("billedserviceunits", value);
			this.OnPropertyChanged("BilledServiceUnits");
		}
	}
	
	/// <summary>
	/// מפרט אם הפרופיל חסום או לא.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("blockedprofile")]
	public System.Nullable<bool> BlockedProfile
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("blockedprofile");
		}
		set
		{
			this.OnPropertyChanging("BlockedProfile");
			this.SetAttributeValue("blockedprofile", value);
			this.OnPropertyChanged("BlockedProfile");
		}
	}
	
	/// <summary>
	/// בחר כיצד נוצר קשר לגבי האירוע, כגון דואר אלקטרוני, טלפון או אינטרנט, למטרות דיווח וניתוח.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("caseorigincode")]
	public Microsoft.Xrm.Sdk.OptionSetValue CaseOriginCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("caseorigincode");
		}
		set
		{
			this.OnPropertyChanging("CaseOriginCode");
			this.SetAttributeValue("caseorigincode", value);
			this.OnPropertyChanged("CaseOriginCode");
		}
	}
	
	/// <summary>
	/// בחר את סוג האירוע כדי לזהות את המקרה למטרות ניתוב וניתוח של אירועים.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("casetypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue CaseTypeCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("casetypecode");
		}
		set
		{
			this.OnPropertyChanging("CaseTypeCode");
			this.SetAttributeValue("casetypecode", value);
			this.OnPropertyChanged("CaseTypeCode");
		}
	}
	
	/// <summary>
	/// תכונה זו משמשת לדוגמאות של תהליכים עסקיים של שירותים.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("checkemail")]
	public System.Nullable<bool> CheckEmail
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("checkemail");
		}
		set
		{
			this.OnPropertyChanging("CheckEmail");
			this.SetAttributeValue("checkemail", value);
			this.OnPropertyChanged("CheckEmail");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של איש הקשר המשויך לאירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactid")]
	public Microsoft.Xrm.Sdk.EntityReference ContactId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contactid");
		}
	}
	
	/// <summary>
	/// בחר את סעיף החוזה שתחתיו יש לרשום את האירוע כדי לוודא שהלקוח מחויב בצורה נכונה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractdetailid")]
	public Microsoft.Xrm.Sdk.EntityReference ContractDetailId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contractdetailid");
		}
		set
		{
			this.OnPropertyChanging("ContractDetailId");
			this.SetAttributeValue("contractdetailid", value);
			this.OnPropertyChanged("ContractDetailId");
		}
	}
	
	/// <summary>
	/// בחר את חוזה השירות שתחתיו יש לרשום את האירוע כדי לוודא שהלקוח זכאי לשירותי תמיכה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractid")]
	public Microsoft.Xrm.Sdk.EntityReference ContractId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contractid");
		}
		set
		{
			this.OnPropertyChanging("ContractId");
			this.SetAttributeValue("contractid", value);
			this.OnPropertyChanged("ContractId");
		}
	}
	
	/// <summary>
	/// בחר את רמת השירות של האירוע כדי לוודא שהאירוע מטופל כראוי.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractservicelevelcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue ContractServiceLevelCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("contractservicelevelcode");
		}
		set
		{
			this.OnPropertyChanging("ContractServiceLevelCode");
			this.SetAttributeValue("contractservicelevelcode", value);
			this.OnPropertyChanged("ContractServiceLevelCode");
		}
	}
	
	/// <summary>
	/// מראה מי יצר את הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// מראה את הצד החיצוני שיצר את הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyexternalparty")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedByExternalParty
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdbyexternalparty");
		}
	}
	
	/// <summary>
	/// התאריך והשעה שבהם נוצרה הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// מראה מי יצר את הרשומה בשמו של משתמש אחר.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// מציין אם נציג שירות לקוחות יצר קשר עם הלקוח או לא.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customercontacted")]
	public System.Nullable<bool> CustomerContacted
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("customercontacted");
		}
		set
		{
			this.OnPropertyChanging("CustomerContacted");
			this.SetAttributeValue("customercontacted", value);
			this.OnPropertyChanged("CustomerContacted");
		}
	}
	
	/// <summary>
	/// בחר את תיק הלקוח או איש הקשר של הלקוח כדי לספק קישור מהיר לפרטי לקוח נוספים, כגון פרטי חשבון, פעילויות והזדמנויות.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
	public Microsoft.Xrm.Sdk.EntityReference CustomerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customerid");
		}
		set
		{
			this.OnPropertyChanging("CustomerId");
			this.SetAttributeValue("customerid", value);
			this.OnPropertyChanged("CustomerId");
		}
	}
	
	/// <summary>
	/// בחר את רמת שביעות הרצון של הלקוח מהטיפול באירוע ופתרונו.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customersatisfactioncode")]
	public Microsoft.Xrm.Sdk.OptionSetValue CustomerSatisfactionCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("customersatisfactioncode");
		}
		set
		{
			this.OnPropertyChanging("CustomerSatisfactionCode");
			this.SetAttributeValue("customersatisfactioncode", value);
			this.OnPropertyChanged("CustomerSatisfactionCode");
		}
	}
	
	/// <summary>
	/// מראה אם יש להפחית את התנאים של הזכאות המשויכת או לא.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("decremententitlementterm")]
	public System.Nullable<bool> DecrementEntitlementTerm
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("decremententitlementterm");
		}
		set
		{
			this.OnPropertyChanging("DecrementEntitlementTerm");
			this.SetAttributeValue("decremententitlementterm", value);
			this.OnPropertyChanged("DecrementEntitlementTerm");
		}
	}
	
	/// <summary>
	/// הקלד מידע נוסף כדי לתאר את האירוע במטרה לסייע לצוות השירות במציאת פתרון.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
	public string Description
	{
		get
		{
			return this.GetAttributeValue<string>("description");
		}
		set
		{
			this.OnPropertyChanging("Description");
			this.SetAttributeValue("description", value);
			this.OnPropertyChanged("Description");
		}
	}
	
	/// <summary>
	/// כתובת הדואר האלקטרוני הראשית של הישות.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
	public string EmailAddress
	{
		get
		{
			return this.GetAttributeValue<string>("emailaddress");
		}
		set
		{
			this.OnPropertyChanging("EmailAddress");
			this.SetAttributeValue("emailaddress", value);
			this.OnPropertyChanged("EmailAddress");
		}
	}
	
	/// <summary>
	/// בחר את הזכאות הישימה עבור האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitlementid")]
	public Microsoft.Xrm.Sdk.EntityReference EntitlementId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("entitlementid");
		}
		set
		{
			this.OnPropertyChanging("EntitlementId");
			this.SetAttributeValue("entitlementid", value);
			this.OnPropertyChanged("EntitlementId");
		}
	}
	
	/// <summary>
	/// תמונת ברירת המחדל עבור הישות.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
	public byte[] EntityImage
	{
		get
		{
			return this.GetAttributeValue<byte[]>("entityimage");
		}
		set
		{
			this.OnPropertyChanging("EntityImage");
			this.SetAttributeValue("entityimage", value);
			this.OnPropertyChanged("EntityImage");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
	public System.Nullable<long> EntityImage_Timestamp
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
	public string EntityImage_URL
	{
		get
		{
			return this.GetAttributeValue<string>("entityimage_url");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
	public System.Nullable<System.Guid> EntityImageId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
		}
	}
	
	/// <summary>
	/// מציין את התאריך והשעה שבהם האירוע הוסלם.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("escalatedon")]
	public System.Nullable<System.DateTime> EscalatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("escalatedon");
		}
	}
	
	/// <summary>
	/// מציג את שער ההמרה של מטבע הרשומה. שער החליפין משמש להמרת כל שדות הכספים ברשומה מהמטבע המקומי למטבע ברירת המחדל של המערכת.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
	public System.Nullable<decimal> ExchangeRate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
		}
	}
	
	/// <summary>
	/// בחר אירוע קיים עבור הלקוח שאוכלס. לשימוש פנימי בלבד.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("existingcase")]
	public Microsoft.Xrm.Sdk.EntityReference ExistingCase
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("existingcase");
		}
		set
		{
			this.OnPropertyChanging("ExistingCase");
			this.SetAttributeValue("existingcase", value);
			this.OnPropertyChanged("ExistingCase");
		}
	}
	
	/// <summary>
	/// ‏‏לשימוש פנימי בלבד.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponsebykpiid")]
	public Microsoft.Xrm.Sdk.EntityReference FirstResponseByKPIId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("firstresponsebykpiid");
		}
		set
		{
			this.OnPropertyChanging("FirstResponseByKPIId");
			this.SetAttributeValue("firstresponsebykpiid", value);
			this.OnPropertyChanged("FirstResponseByKPIId");
		}
	}
	
	/// <summary>
	/// מציין אם התגובה הראשונה נשלחה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponsesent")]
	public System.Nullable<bool> FirstResponseSent
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("firstresponsesent");
		}
		set
		{
			this.OnPropertyChanging("FirstResponseSent");
			this.SetAttributeValue("firstresponsesent", value);
			this.OnPropertyChanged("FirstResponseSent");
		}
	}
	
	/// <summary>
	/// מציג את המצב של זמן התגובה הראשוני עבור האירוע בהתאם לתנאי ה- SLA.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponseslastatus")]
	public Microsoft.Xrm.Sdk.OptionSetValue FirstResponseSLAStatus
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("firstresponseslastatus");
		}
		set
		{
			this.OnPropertyChanging("FirstResponseSLAStatus");
			this.SetAttributeValue("firstresponseslastatus", value);
			this.OnPropertyChanged("FirstResponseSLAStatus");
		}
	}
	
	/// <summary>
	/// הזן את התאריך שעד אליו נציג שירות לקוחות צריך לבצע את המשך הטיפול באירוע זה מול הלקוח.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("followupby")]
	public System.Nullable<System.DateTime> FollowupBy
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("followupby");
		}
		set
		{
			this.OnPropertyChanging("FollowupBy");
			this.SetAttributeValue("followupby", value);
			this.OnPropertyChanged("FollowupBy");
		}
	}
	
	/// <summary>
	/// תכונה זו משמשת לדוגמאות של תהליכים עסקיים של שירותים.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("followuptaskcreated")]
	public System.Nullable<bool> FollowUpTaskCreated
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("followuptaskcreated");
		}
		set
		{
			this.OnPropertyChanging("FollowUpTaskCreated");
			this.SetAttributeValue("followuptaskcreated", value);
			this.OnPropertyChanged("FollowUpTaskCreated");
		}
	}
	
	/// <summary>
	/// מספר הרצף של הייבוא שיצר רשומה זו.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentid")]
	public System.Nullable<System.Guid> IncidentId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("incidentid");
		}
		set
		{
			this.OnPropertyChanging("IncidentId");
			this.SetAttributeValue("incidentid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("IncidentId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.IncidentId = value;
		}
	}
	
	/// <summary>
	/// בחר את השלב הנוכחי של תהליך השירות עבור האירוע כדי לסייע לחברי צוות השירות כאשר הם סוקרים או מעבירים אירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentstagecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue IncidentStageCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("incidentstagecode");
		}
		set
		{
			this.OnPropertyChanging("IncidentStageCode");
			this.SetAttributeValue("incidentstagecode", value);
			this.OnPropertyChanged("IncidentStageCode");
		}
	}
	
	/// <summary>
	/// יכיל את ניקוד בעל ההשפעה המגיע מ- NetBreeze.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("influencescore")]
	public System.Nullable<double> InfluenceScore
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<double>>("influencescore");
		}
		set
		{
			this.OnPropertyChanging("InfluenceScore");
			this.SetAttributeValue("influencescore", value);
			this.OnPropertyChanged("InfluenceScore");
		}
	}
	
	/// <summary>
	/// לשימוש המערכת בלבד.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdecrementing")]
	public System.Nullable<bool> IsDecrementing
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("isdecrementing");
		}
		set
		{
			this.OnPropertyChanging("IsDecrementing");
			this.SetAttributeValue("isdecrementing", value);
			this.OnPropertyChanged("IsDecrementing");
		}
	}
	
	/// <summary>
	/// מציין אם האירוע הוסלם.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isescalated")]
	public System.Nullable<bool> IsEscalated
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("isescalated");
		}
		set
		{
			this.OnPropertyChanging("IsEscalated");
			this.SetAttributeValue("isescalated", value);
			this.OnPropertyChanged("IsEscalated");
		}
	}
	
	/// <summary>
	/// בחר את המאמר המכיל מידע נוסף או פתרון לאירוע, לצורך עיון במהלך מחקר או המשך טיפול מול הלקוח.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("kbarticleid")]
	public Microsoft.Xrm.Sdk.EntityReference KbArticleId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("kbarticleid");
		}
		set
		{
			this.OnPropertyChanging("KbArticleId");
			this.SetAttributeValue("kbarticleid", value);
			this.OnPropertyChanged("KbArticleId");
		}
	}
	
	/// <summary>
	/// מכיל את חותמת התאריך והשעה של זמן ההמתנה האחרון.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastonholdtime")]
	public System.Nullable<System.DateTime> LastOnHoldTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
		}
		set
		{
			this.OnPropertyChanging("LastOnHoldTime");
			this.SetAttributeValue("lastonholdtime", value);
			this.OnPropertyChanged("LastOnHoldTime");
		}
	}
	
	/// <summary>
	/// בחר את האירוע הראשי שהאירוע הנוכחי מוזג לתוכו.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("masterid")]
	public Microsoft.Xrm.Sdk.EntityReference MasterId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("masterid");
		}
		set
		{
			this.OnPropertyChanging("MasterId");
			this.SetAttributeValue("masterid", value);
			this.OnPropertyChanged("MasterId");
		}
	}
	
	/// <summary>
	/// מציין אם המקרה מוזג עם מקרה אחר.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("merged")]
	public System.Nullable<bool> Merged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("merged");
		}
	}
	
	/// <summary>
	/// מראה אם הפרסום נוצר כהודעה ציבורית או פרטית.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("messagetypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue MessageTypeCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("messagetypecode");
		}
		set
		{
			this.OnPropertyChanging("MessageTypeCode");
			this.SetAttributeValue("messagetypecode", value);
			this.OnPropertyChanged("MessageTypeCode");
		}
	}
	
	/// <summary>
	/// מראה מי עדכן לאחרונה את הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// מראה את הצד החיצוני ששינה את הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyexternalparty")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedByExternalParty
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedbyexternalparty");
		}
	}
	
	/// <summary>
	/// התאריך והשעה שבהם השתנתה הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// מראה מי עדכן לאחרונה את הרשומה בשמו של משתמש אחר.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// התראת ה- IoT שאתחלה אירוע זה
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_iotalert")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_iotalert
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_iotalert");
		}
		set
		{
			this.OnPropertyChanging("msdyn_iotalert");
			this.SetAttributeValue("msdyn_iotalert", value);
			this.OnPropertyChanged("msdyn_iotalert");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_accountid")]
	public Microsoft.Xrm.Sdk.EntityReference mtx_AccountId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mtx_accountid");
		}
		set
		{
			this.OnPropertyChanging("mtx_AccountId");
			this.SetAttributeValue("mtx_accountid", value);
			this.OnPropertyChanged("mtx_AccountId");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_address")]
	public string mtx_Address
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_address");
		}
		set
		{
			this.OnPropertyChanging("mtx_Address");
			this.SetAttributeValue("mtx_address", value);
			this.OnPropertyChanged("mtx_Address");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_appointmentdescription")]
	public string mtx_AppointmentDescription
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_appointmentdescription");
		}
		set
		{
			this.OnPropertyChanging("mtx_AppointmentDescription");
			this.SetAttributeValue("mtx_appointmentdescription", value);
			this.OnPropertyChanged("mtx_AppointmentDescription");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_appointmentname")]
	public string mtx_AppointmentName
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_appointmentname");
		}
		set
		{
			this.OnPropertyChanging("mtx_AppointmentName");
			this.SetAttributeValue("mtx_appointmentname", value);
			this.OnPropertyChanged("mtx_AppointmentName");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_assigningranks")]
	public string mtx_AssigningRanks
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_assigningranks");
		}
		set
		{
			this.OnPropertyChanging("mtx_AssigningRanks");
			this.SetAttributeValue("mtx_assigningranks", value);
			this.OnPropertyChanged("mtx_AssigningRanks");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_assistancedescription")]
	public string mtx_AssistanceDescription
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_assistancedescription");
		}
		set
		{
			this.OnPropertyChanging("mtx_AssistanceDescription");
			this.SetAttributeValue("mtx_assistancedescription", value);
			this.OnPropertyChanged("mtx_AssistanceDescription");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_assistant")]
	public string mtx_Assistant
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_assistant");
		}
		set
		{
			this.OnPropertyChanging("mtx_Assistant");
			this.SetAttributeValue("mtx_assistant", value);
			this.OnPropertyChanged("mtx_Assistant");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_branch")]
	public string mtx_Branch
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_branch");
		}
		set
		{
			this.OnPropertyChanging("mtx_Branch");
			this.SetAttributeValue("mtx_branch", value);
			this.OnPropertyChanged("mtx_Branch");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_citizensparticipationbit")]
	public System.Nullable<bool> mtx_CitizensParticipationBit
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("mtx_citizensparticipationbit");
		}
		set
		{
			this.OnPropertyChanging("mtx_CitizensParticipationBit");
			this.SetAttributeValue("mtx_citizensparticipationbit", value);
			this.OnPropertyChanged("mtx_CitizensParticipationBit");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_comments")]
	public string mtx_Comments
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_comments");
		}
		set
		{
			this.OnPropertyChanging("mtx_Comments");
			this.SetAttributeValue("mtx_comments", value);
			this.OnPropertyChanged("mtx_Comments");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_contactid")]
	public Microsoft.Xrm.Sdk.EntityReference mtx_ContactId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mtx_contactid");
		}
		set
		{
			this.OnPropertyChanging("mtx_ContactId");
			this.SetAttributeValue("mtx_contactid", value);
			this.OnPropertyChanged("mtx_ContactId");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_cosedate")]
	public System.Nullable<System.DateTime> mtx_CoseDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mtx_cosedate");
		}
		set
		{
			this.OnPropertyChanging("mtx_CoseDate");
			this.SetAttributeValue("mtx_cosedate", value);
			this.OnPropertyChanged("mtx_CoseDate");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_department")]
	public string mtx_Department
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_department");
		}
		set
		{
			this.OnPropertyChanging("mtx_Department");
			this.SetAttributeValue("mtx_department", value);
			this.OnPropertyChanged("mtx_Department");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_educationcode")]
	public Microsoft.Xrm.Sdk.OptionSetValue mtx_EducationCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mtx_educationcode");
		}
		set
		{
			this.OnPropertyChanging("mtx_EducationCode");
			this.SetAttributeValue("mtx_educationcode", value);
			this.OnPropertyChanged("mtx_EducationCode");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_enddate")]
	public System.Nullable<System.DateTime> mtx_EndDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mtx_enddate");
		}
		set
		{
			this.OnPropertyChanging("mtx_EndDate");
			this.SetAttributeValue("mtx_enddate", value);
			this.OnPropertyChanged("mtx_EndDate");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_eventdate")]
	public System.Nullable<System.DateTime> mtx_EventDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mtx_eventdate");
		}
		set
		{
			this.OnPropertyChanging("mtx_EventDate");
			this.SetAttributeValue("mtx_eventdate", value);
			this.OnPropertyChanged("mtx_EventDate");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_eventlocation")]
	public string mtx_EventLocation
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_eventlocation");
		}
		set
		{
			this.OnPropertyChanging("mtx_EventLocation");
			this.SetAttributeValue("mtx_eventlocation", value);
			this.OnPropertyChanged("mtx_EventLocation");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_eventtypecode")]
	public Microsoft.Xrm.Sdk.OptionSetValue mtx_EventTypeCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mtx_eventtypecode");
		}
		set
		{
			this.OnPropertyChanging("mtx_EventTypeCode");
			this.SetAttributeValue("mtx_eventtypecode", value);
			this.OnPropertyChanged("mtx_EventTypeCode");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_freezingenddate")]
	public System.Nullable<System.DateTime> mtx_FreezingEndDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mtx_freezingenddate");
		}
		set
		{
			this.OnPropertyChanging("mtx_FreezingEndDate");
			this.SetAttributeValue("mtx_freezingenddate", value);
			this.OnPropertyChanged("mtx_FreezingEndDate");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_freezingstartdate")]
	public System.Nullable<System.DateTime> mtx_FreezingStartDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mtx_freezingstartdate");
		}
		set
		{
			this.OnPropertyChanging("mtx_FreezingStartDate");
			this.SetAttributeValue("mtx_freezingstartdate", value);
			this.OnPropertyChanged("mtx_FreezingStartDate");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_gendercode")]
	public Microsoft.Xrm.Sdk.OptionSetValue mtx_GenderCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mtx_gendercode");
		}
		set
		{
			this.OnPropertyChanging("mtx_GenderCode");
			this.SetAttributeValue("mtx_gendercode", value);
			this.OnPropertyChanged("mtx_GenderCode");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_iscontributingbit")]
	public System.Nullable<bool> mtx_IsContributingBit
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("mtx_iscontributingbit");
		}
		set
		{
			this.OnPropertyChanging("mtx_IsContributingBit");
			this.SetAttributeValue("mtx_iscontributingbit", value);
			this.OnPropertyChanged("mtx_IsContributingBit");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_isfilerequiredforreadingbit")]
	public System.Nullable<bool> mtx_IsFileRequiredForReadingBit
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("mtx_isfilerequiredforreadingbit");
		}
		set
		{
			this.OnPropertyChanging("mtx_IsFileRequiredForReadingBit");
			this.SetAttributeValue("mtx_isfilerequiredforreadingbit", value);
			this.OnPropertyChanged("mtx_IsFileRequiredForReadingBit");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_isrequiredfilebit")]
	public System.Nullable<bool> mtx_IsRequiredFileBit
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("mtx_isrequiredfilebit");
		}
		set
		{
			this.OnPropertyChanging("mtx_IsRequiredFileBit");
			this.SetAttributeValue("mtx_isrequiredfilebit", value);
			this.OnPropertyChanged("mtx_IsRequiredFileBit");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_issentmanagerapprovalbit")]
	public System.Nullable<bool> mtx_IsSentManagerApprovalBit
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("mtx_issentmanagerapprovalbit");
		}
		set
		{
			this.OnPropertyChanging("mtx_IsSentManagerApprovalBit");
			this.SetAttributeValue("mtx_issentmanagerapprovalbit", value);
			this.OnPropertyChanged("mtx_IsSentManagerApprovalBit");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_issubmittedrightbit")]
	public System.Nullable<bool> mtx_IsSubmittedRightBit
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("mtx_issubmittedrightbit");
		}
		set
		{
			this.OnPropertyChanging("mtx_IsSubmittedRightBit");
			this.SetAttributeValue("mtx_issubmittedrightbit", value);
			this.OnPropertyChanged("mtx_IsSubmittedRightBit");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_populationtypeid")]
	public Microsoft.Xrm.Sdk.EntityReference mtx_PopulationTypeId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mtx_populationtypeid");
		}
		set
		{
			this.OnPropertyChanging("mtx_PopulationTypeId");
			this.SetAttributeValue("mtx_populationtypeid", value);
			this.OnPropertyChanged("mtx_PopulationTypeId");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_prefixid")]
	public Microsoft.Xrm.Sdk.EntityReference mtx_PrefixId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mtx_prefixid");
		}
		set
		{
			this.OnPropertyChanging("mtx_PrefixId");
			this.SetAttributeValue("mtx_prefixid", value);
			this.OnPropertyChanged("mtx_PrefixId");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_professionallevelcode")]
	public string mtx_ProfessionalLevelCode
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_professionallevelcode");
		}
		set
		{
			this.OnPropertyChanging("mtx_ProfessionalLevelCode");
			this.SetAttributeValue("mtx_professionallevelcode", value);
			this.OnPropertyChanged("mtx_ProfessionalLevelCode");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_professionid")]
	public Microsoft.Xrm.Sdk.EntityReference mtx_ProfessionId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mtx_professionid");
		}
		set
		{
			this.OnPropertyChanging("mtx_ProfessionId");
			this.SetAttributeValue("mtx_professionid", value);
			this.OnPropertyChanged("mtx_ProfessionId");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_rejectedreason")]
	public string mtx_rejectedReason
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_rejectedreason");
		}
		set
		{
			this.OnPropertyChanging("mtx_rejectedReason");
			this.SetAttributeValue("mtx_rejectedreason", value);
			this.OnPropertyChanged("mtx_rejectedReason");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_requestnumberint")]
	public System.Nullable<int> mtx_RequestNumberInt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("mtx_requestnumberint");
		}
		set
		{
			this.OnPropertyChanging("mtx_RequestNumberInt");
			this.SetAttributeValue("mtx_requestnumberint", value);
			this.OnPropertyChanged("mtx_RequestNumberInt");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_resolveddate")]
	public System.Nullable<System.DateTime> mtx_ResolvedDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mtx_resolveddate");
		}
		set
		{
			this.OnPropertyChanging("mtx_ResolvedDate");
			this.SetAttributeValue("mtx_resolveddate", value);
			this.OnPropertyChanged("mtx_ResolvedDate");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_seniorperson")]
	public string mtx_SeniorPerson
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_seniorperson");
		}
		set
		{
			this.OnPropertyChanging("mtx_SeniorPerson");
			this.SetAttributeValue("mtx_seniorperson", value);
			this.OnPropertyChanged("mtx_SeniorPerson");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_soldierjobid")]
	public Microsoft.Xrm.Sdk.EntityReference mtx_SoldierJobId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mtx_soldierjobid");
		}
		set
		{
			this.OnPropertyChanging("mtx_SoldierJobId");
			this.SetAttributeValue("mtx_soldierjobid", value);
			this.OnPropertyChanged("mtx_SoldierJobId");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_topicrequiredid")]
	public Microsoft.Xrm.Sdk.EntityReference mtx_TopicRequiredId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mtx_topicrequiredid");
		}
		set
		{
			this.OnPropertyChanging("mtx_TopicRequiredId");
			this.SetAttributeValue("mtx_topicrequiredid", value);
			this.OnPropertyChanged("mtx_TopicRequiredId");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_totalparticipantsnumint")]
	public System.Nullable<int> mtx_TotalParticipantsNumInt
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("mtx_totalparticipantsnumint");
		}
		set
		{
			this.OnPropertyChanging("mtx_TotalParticipantsNumInt");
			this.SetAttributeValue("mtx_totalparticipantsnumint", value);
			this.OnPropertyChanged("mtx_TotalParticipantsNumInt");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_treatmentdescription")]
	public string mtx_TreatmentDescription
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_treatmentdescription");
		}
		set
		{
			this.OnPropertyChanging("mtx_TreatmentDescription");
			this.SetAttributeValue("mtx_treatmentdescription", value);
			this.OnPropertyChanged("mtx_TreatmentDescription");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_tripdate")]
	public System.Nullable<System.DateTime> mtx_TripDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mtx_tripdate");
		}
		set
		{
			this.OnPropertyChanging("mtx_TripDate");
			this.SetAttributeValue("mtx_tripdate", value);
			this.OnPropertyChanged("mtx_TripDate");
		}
	}
	
	/// <summary>
	/// 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mtx_tripplan")]
	public string mtx_TripPlan
	{
		get
		{
			return this.GetAttributeValue<string>("mtx_tripplan");
		}
		set
		{
			this.OnPropertyChanging("mtx_TripPlan");
			this.SetAttributeValue("mtx_tripplan", value);
			this.OnPropertyChanged("mtx_TripPlan");
		}
	}
	
	/// <summary>
	/// מספר מקרי הצאצא המשויכים למקרה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numberofchildincidents")]
	public System.Nullable<int> NumberOfChildIncidents
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("numberofchildincidents");
		}
	}
	
	/// <summary>
	/// מציג את המשך בדקות שבו האירוע היה בהמתנה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("onholdtime")]
	public System.Nullable<int> OnHoldTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
		}
	}
	
	/// <summary>
	/// התאריך והשעה שבהם הועברה הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// מזהה בעלים
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של היחידה העסקית שהרשומה נמצאת בבעלותה
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// ‏‏ה‏‏מזהה הייחודי של הצוות שהרשומה נמצאת בבעלותו.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של המשתמש שהרשומה נמצאת בבעלותו.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// בחר את אירוע האב של אירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcaseid")]
	public Microsoft.Xrm.Sdk.EntityReference ParentCaseId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentcaseid");
		}
		set
		{
			this.OnPropertyChanging("ParentCaseId");
			this.SetAttributeValue("parentcaseid", value);
			this.OnPropertyChanged("ParentCaseId");
		}
	}
	
	/// <summary>
	/// בחר איש קשר ראשי עבור אירוע זה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primarycontactid")]
	public Microsoft.Xrm.Sdk.EntityReference PrimaryContactId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("primarycontactid");
		}
		set
		{
			this.OnPropertyChanging("PrimaryContactId");
			this.SetAttributeValue("primarycontactid", value);
			this.OnPropertyChanged("PrimaryContactId");
		}
	}
	
	/// <summary>
	/// בחר את העדיפות כך שלקוחות מועדפים או בעיות קריטיות יטופלו במהירות.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("prioritycode")]
	public Microsoft.Xrm.Sdk.OptionSetValue PriorityCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("prioritycode");
		}
		set
		{
			this.OnPropertyChanging("PriorityCode");
			this.SetAttributeValue("prioritycode", value);
			this.OnPropertyChanged("PriorityCode");
		}
	}
	
	/// <summary>
	/// מכיל את מזהה התהליך המשויך לישות.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
	public System.Nullable<System.Guid> ProcessId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
		}
		set
		{
			this.OnPropertyChanging("ProcessId");
			this.SetAttributeValue("processid", value);
			this.OnPropertyChanged("ProcessId");
		}
	}
	
	/// <summary>
	/// בחר את המוצר המשויך לאירוע כדי לזהות בעיות אחריות, בעיות שירות או בעיות אחרות במוצר ולאפשר דיווח על מספר המקרים לכל מוצר.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productid")]
	public Microsoft.Xrm.Sdk.EntityReference ProductId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("productid");
		}
		set
		{
			this.OnPropertyChanging("ProductId");
			this.SetAttributeValue("productid", value);
			this.OnPropertyChanged("ProductId");
		}
	}
	
	/// <summary>
	/// הקלד את המספר הסידורי של המוצר המשויך לאירוע זה, כך שניתן יהיה לדווח על מספר האירועים לכל מוצר.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productserialnumber")]
	public string ProductSerialNumber
	{
		get
		{
			return this.GetAttributeValue<string>("productserialnumber");
		}
		set
		{
			this.OnPropertyChanging("ProductSerialNumber");
			this.SetAttributeValue("productserialnumber", value);
			this.OnPropertyChanged("ProductSerialNumber");
		}
	}
	
	/// <summary>
	/// הזן את התאריך שעד אליו יש לפתור את האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolveby")]
	public System.Nullable<System.DateTime> ResolveBy
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("resolveby");
		}
		set
		{
			this.OnPropertyChanging("ResolveBy");
			this.SetAttributeValue("resolveby", value);
			this.OnPropertyChanged("ResolveBy");
		}
	}
	
	/// <summary>
	/// ‏‏לשימוש פנימי בלבד.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolvebykpiid")]
	public Microsoft.Xrm.Sdk.EntityReference ResolveByKPIId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("resolvebykpiid");
		}
		set
		{
			this.OnPropertyChanging("ResolveByKPIId");
			this.SetAttributeValue("resolvebykpiid", value);
			this.OnPropertyChanged("ResolveByKPIId");
		}
	}
	
	/// <summary>
	/// מציג את המצב של זמן הפתרון עבור האירוע בהתאם לתנאי ה- SLA.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolvebyslastatus")]
	public Microsoft.Xrm.Sdk.OptionSetValue ResolveBySLAStatus
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("resolvebyslastatus");
		}
		set
		{
			this.OnPropertyChanging("ResolveBySLAStatus");
			this.SetAttributeValue("resolvebyslastatus", value);
			this.OnPropertyChanged("ResolveBySLAStatus");
		}
	}
	
	/// <summary>
	/// ‏‏לשימוש פנימי בלבד.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("responseby")]
	public System.Nullable<System.DateTime> ResponseBy
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("responseby");
		}
		set
		{
			this.OnPropertyChanging("ResponseBy");
			this.SetAttributeValue("responseby", value);
			this.OnPropertyChanged("ResponseBy");
		}
	}
	
	/// <summary>
	/// בחר איש קשר נוסף של לקוח שיכול גם הוא לעזור לפתור את האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("responsiblecontactid")]
	[System.ObsoleteAttribute()]
	public Microsoft.Xrm.Sdk.EntityReference ResponsibleContactId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("responsiblecontactid");
		}
		set
		{
			this.OnPropertyChanging("ResponsibleContactId");
			this.SetAttributeValue("responsiblecontactid", value);
			this.OnPropertyChanged("ResponsibleContactId");
		}
	}
	
	/// <summary>
	/// מציין אם המקרה נותב לתור או לא.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("routecase")]
	public System.Nullable<bool> RouteCase
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("routecase");
		}
		set
		{
			this.OnPropertyChanging("RouteCase");
			this.SetAttributeValue("routecase", value);
			this.OnPropertyChanged("RouteCase");
		}
	}
	
	/// <summary>
	/// הערך שנגזר לאחר הערכת מילים המשויכות בדרך כלל לסנטימנט שלילי, ניטראלי או חיובי בפרסום חברתי. ניתן גם לדווח על פרטי סנטימנט כערכים מספריים.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sentimentvalue")]
	public System.Nullable<double> SentimentValue
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<double>>("sentimentvalue");
		}
		set
		{
			this.OnPropertyChanging("SentimentValue");
			this.SetAttributeValue("sentimentvalue", value);
			this.OnPropertyChanged("SentimentValue");
		}
	}
	
	/// <summary>
	/// בחר את השלב שבו נמצא האירוע בתהליך פתרון האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("servicestage")]
	public Microsoft.Xrm.Sdk.OptionSetValue ServiceStage
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("servicestage");
		}
		set
		{
			this.OnPropertyChanging("ServiceStage");
			this.SetAttributeValue("servicestage", value);
			this.OnPropertyChanged("ServiceStage");
		}
	}
	
	/// <summary>
	/// בחר את חומרת אירוע זה כדי לציין את ההשפעה של המקרה על העסק של הלקוח.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("severitycode")]
	public Microsoft.Xrm.Sdk.OptionSetValue SeverityCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("severitycode");
		}
		set
		{
			this.OnPropertyChanging("SeverityCode");
			this.SetAttributeValue("severitycode", value);
			this.OnPropertyChanged("SeverityCode");
		}
	}
	
	/// <summary>
	/// בחר את הסכם רמת השירות (SLA) שברצונך להחיל על רשומת האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
	public Microsoft.Xrm.Sdk.EntityReference SLAId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
		}
		set
		{
			this.OnPropertyChanging("SLAId");
			this.SetAttributeValue("slaid", value);
			this.OnPropertyChanged("SLAId");
		}
	}
	
	/// <summary>
	/// ה- SLA האחרון שהוחל על אירוע זה. שדה זה מיועד לשימוש פנימי בלבד.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
	public Microsoft.Xrm.Sdk.EntityReference SLAInvokedId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slainvokedid");
		}
	}
	
	/// <summary>
	/// המזהה הייחודי של הפרופיל החברתי שאליו משויך האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("socialprofileid")]
	public Microsoft.Xrm.Sdk.EntityReference SocialProfileId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("socialprofileid");
		}
		set
		{
			this.OnPropertyChanging("SocialProfileId");
			this.SetAttributeValue("socialprofileid", value);
			this.OnPropertyChanged("SocialProfileId");
		}
	}
	
	/// <summary>
	/// מכיל את מזהה השלב שבו הישות ממוקמת.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
	public System.Nullable<System.Guid> StageId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
		}
		set
		{
			this.OnPropertyChanging("StageId");
			this.SetAttributeValue("stageid", value);
			this.OnPropertyChanged("StageId");
		}
	}
	
	/// <summary>
	/// מראה אם האירוע פעיל, נפתר או בוטל. אירועים שנפתרו ואירועים שבוטלו מוגדרים לקריאה בלבד ולא ניתן לערוך אותם אלא אם הם מופעלים מחדש.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public System.Nullable<IncidentState> StateCode
	{
		get
		{
			Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
			if ((optionSet != null))
			{
				return ((IncidentState)(System.Enum.ToObject(typeof(IncidentState), optionSet.Value)));
			}
			else
			{
				return null;
			}
		}
		set
		{
			this.OnPropertyChanging("StateCode");
			if ((value == null))
			{
				this.SetAttributeValue("statecode", null);
			}
			else
			{
				this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
			}
			this.OnPropertyChanged("StateCode");
		}
	}
	
	/// <summary>
	/// בחר את מצב האירוע.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
		}
		set
		{
			this.OnPropertyChanging("StatusCode");
			this.SetAttributeValue("statuscode", value);
			this.OnPropertyChanged("StatusCode");
		}
	}
	
	/// <summary>
	/// בחר את הנושא עבור האירוע, כגון בקשה לקטלוג או תלונה על מוצר, כך שמנהלי שירות לקוחות יוכלו לזהות בקשות תכופות או אזורים בעייתיים. מנהלי מערכת יכולים לקבוע את התצורה של נושאים תחת 'ניהול עסקי‬' באזור 'הגדרות'.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectid")]
	public Microsoft.Xrm.Sdk.EntityReference SubjectId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("subjectid");
		}
		set
		{
			this.OnPropertyChanging("SubjectId");
			this.SetAttributeValue("subjectid", value);
			this.OnPropertyChanged("SubjectId");
		}
	}
	
	/// <summary>
	/// מציג את מספר האירוע לצורך חיפוש ועיון בפרטי לקוחות. אין אפשרות לשנות זאת.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ticketnumber")]
	public string TicketNumber
	{
		get
		{
			return this.GetAttributeValue<string>("ticketnumber");
		}
		set
		{
			this.OnPropertyChanging("TicketNumber");
			this.SetAttributeValue("ticketnumber", value);
			this.OnPropertyChanged("TicketNumber");
		}
	}
	
	/// <summary>
	/// ‏‏לשימוש פנימי בלבד.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// הקלד נושא או שם תיאורי, כגון הבקשה, הבעיה או שם החברה, כדי לזהות את האירוע בתצוגות Microsoft Dynamics 365.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
	public string Title
	{
		get
		{
			return this.GetAttributeValue<string>("title");
		}
		set
		{
			this.OnPropertyChanging("Title");
			this.SetAttributeValue("title", value);
			this.OnPropertyChanged("Title");
		}
	}
	
	/// <summary>
	/// בחר את המטבע המקומי עבור הרשומה כדי לוודא שתקציבים מדווחים במטבע הנכון.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
		}
		set
		{
			this.OnPropertyChanging("TransactionCurrencyId");
			this.SetAttributeValue("transactioncurrencyid", value);
			this.OnPropertyChanged("TransactionCurrencyId");
		}
	}
	
	/// <summary>
	/// רשימה מופרדת באמצעות פסיקים של ערכי מחרוזות המייצגים את המזהים הייחודיים של שלבים במופע של זרימת תהליך עסקי, בסדר שבו הם מתרחשים.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
	public string TraversedPath
	{
		get
		{
			return this.GetAttributeValue<string>("traversedpath");
		}
		set
		{
			this.OnPropertyChanging("TraversedPath");
			this.SetAttributeValue("traversedpath", value);
			this.OnPropertyChanged("TraversedPath");
		}
	}
	
	/// <summary>
	/// ‏‏קוד אזור הזמן שהיה בשימוש בעת יצירת הרשומה.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// מספר גירסה
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N incident_existingcase
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<Incident> Referencedincident_existingcase
	{
		get
		{
			return this.GetRelatedEntities<Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedincident_existingcase");
			this.SetRelatedEntities<Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedincident_existingcase");
		}
	}
	
	/// <summary>
	/// 1:N incident_master_incident
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<Incident> Referencedincident_master_incident
	{
		get
		{
			return this.GetRelatedEntities<Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedincident_master_incident");
			this.SetRelatedEntities<Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedincident_master_incident");
		}
	}
	
	/// <summary>
	/// 1:N incident_parent_incident
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<Incident> Referencedincident_parent_incident
	{
		get
		{
			return this.GetRelatedEntities<Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedincident_parent_incident");
			this.SetRelatedEntities<Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedincident_parent_incident");
		}
	}
	
	/// <summary>
	/// N:1 incident_existingcase
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("existingcase")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public Incident Referencingincident_existingcase
	{
		get
		{
			return this.GetRelatedEntity<Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingincident_existingcase");
			this.SetRelatedEntity<Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingincident_existingcase");
		}
	}
	
	/// <summary>
	/// N:1 incident_master_incident
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("masterid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public Incident Referencingincident_master_incident
	{
		get
		{
			return this.GetRelatedEntity<Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingincident_master_incident");
			this.SetRelatedEntity<Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingincident_master_incident");
		}
	}
	
	/// <summary>
	/// N:1 incident_parent_incident
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcaseid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public Incident Referencingincident_parent_incident
	{
		get
		{
			return this.GetRelatedEntity<Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingincident_parent_incident");
			this.SetRelatedEntity<Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingincident_parent_incident");
		}
	}
}
